version: "3.8"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/.
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    container_name: mariadb
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception_network

  nginx:
    build: requirements/nginx/.
    env_file:
      - .env
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_MAIL: ${WORDPRESS_USER_MAIL}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge

volumes:
  wordpress_files:
    driver_opts:
      type: "none"
      o: bind
      device: /Users/martinrabat/data/wordpress_files
  wordpress_db:
    driver_opts:
      type: "none"
      o: bind
      device: /Users/martinrabat/data/wordpress_db
